In [ ]:
# H0=PClass and Survived are independent Columns

In [171]:
import pandas as pd
import numpy as np
from scipy.stats import chi2
from scipy.stats import chi2_contingency
# Load the Titanic dataset
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
data = pd.read_csv(url)
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [154]:
df=pd.crosstab(data['Survived'],data['Pclass'],margins=True, margins_name='Total')
df_copy=df.copy()
df

Pclass      1    2    3  Total
Survived
0          80   97  372    549
1         136   87  119    342
Total     216  184  491    891

In [155]:
df_copy

Pclass      1    2    3  Total
Survived
0          80   97  372    549
1         136   87  119    342
Total     216  184  491    891

In [161]:
Grand_Total=df.loc["Total","Total"]
for i in range(df.shape[0]-1):
    for j in range(1,df.shape[1]):
      df_copy.loc[i,j]=(df.loc[i,'Total']*df.loc['Total',j]//Grand_Total)
df_copy

Pclass        1      2      3  Total
Survived
0         133.0  113.0  302.0    549
1          82.0   70.0  188.0    342
Total     216.0  184.0  491.0    891

In [164]:
X=0
for i in range(df.shape[0]-1):
    for j in range(1,df.shape[1]):
      X+=(df.loc[i,j]-df_copy.loc[i,j])**2/df_copy.loc[i,j]
X

np.float64(104.62496816389125)

In [166]:
degree_of_freedom=df.shape[1]-2
p_value=chi2.sf(X,df=degree_of_freedom)
p_value

np.float64(1.9097513625652786e-23)

In [168]:
alpha=0.05
if(p_value<alpha):
    print('Reject the Null Hypothesis')
else:
     print('Failed to Reject the Null Hypothesis')

Reject the Null Hypothesis

In [172]:
contingency_table = pd.crosstab(data['Survived'], data['Pclass'])
contingency_table

Pclass      1   2    3
Survived
0          80  97  372
1         136  87  119

In [ ]:
# Using chi2_contingency

In [179]:
chi2, p_value, dof, expected = chi2_contingency(contingency_table)

print("\nChi-Square Statistic: {:.2f}".format(chi2))
print("P-value: {:.4f}".format(p_value))
print("Degrees of Freedom: {}".format(dof))
print("Expected Frequencies: \n{}".format(expected))

Chi-Square Statistic: 102.89
P-value: 0.0000
Degrees of Freedom: 2
Expected Frequencies:
[[133.09090909 113.37373737 302.53535354]
 [ 82.90909091  70.62626263 188.46464646]]

In [174]:
alpha=0.05
if(p_value<alpha):
    print('Reject the Null Hypothesis')
else:
     print('Failed to Reject the Null Hypothesis')

Reject the Null Hypothesis